source("setup.R")

# grounded theory
# start with a blank slate
# pull out keywords --- things repeated multiple times
# categorize them
# go through and code things that have been categorized

afterbrief$Q1
#  [1] "They are trying to find the right word"
#  [2] "thoughtfulness, unclear thinking, distracted, hesitation, knowledgeable"
#  [3] "Someone either is unsure of what to say and is hesitant or someone speaks faster than they think!"
#  [4] "They are thinking of what to say next, or some use it out of habit"
#  [5] "I think it means that the speaker needs more time to collect their thoughts, or it can be that they are hesitant to say or share something."
#  [6] "They aren't confident with what they are saying or cannot think of a word or phrase that would fit with what they are trying to say (like a buffer)"
#  [7] "I think they feel more hesitant or confused about something."
#  [8] "That they're unsure about an answer and trying to think of one. I think the use of these also relate to a person's self-confidence (don't have faith in their own abilities) and honesty (trying to think of an excuse). "
#  [9] "theyre hesitant, also unconfident in what theyre saying. sometimes also makes them seem unintelligent"
# [10] "they are hesitant, nervous, or don't quite know what to say"
# [11] "Either hesitation or they're using the time to think of a response instead of just saying the first thing that pops up."
# [12] "Hesitation, contemplation "
# [13] "the person is uncomfortable, hesitant or anxious "
# [14] "They are trying to gather their thoughts, simply just put them in there for no reason, maybe trying to approach a subject more cautiously/with more hesitance"
# [15] "That they are unsure of themselves or what they are trying to say"
# [16] "i don't really think it means anything to me. since its a regular part of mine and my friends' speech, i don't detect it as anything other than perhaps \"they're trying to gather their thoughts\""
# [17] "Filler when trying to come up with words but just not in time, or because of habit"
# [18] "I know they are hedging words; they \"soften\" what is going to be said next and express hesitation or politeness."
# [19] "I think it means they either don't know exactly what they want to say or that they want to make whatever they are going to say softer. "
# [20] "When someone uses \"uh\" or \"um\" I usually correlate that with hesitance "
# [21] "Thinking, trying to soften what they say, hesitance"
# [22] "either thinking or hesitate to say something"
# [23] "They're trying to piece together what to say next."
# [24] "They are thinking "
# [25] "signs of casualness and uncertainty and hesitation"
# [26] "It just means they are thinking of the proper words they want to use to convey a certain thought they are having."
# [27] "that they are thinking"
# [28] "Uh or um is an indication of hesitation. I would expect someone to use it when they are nervous, or when a speaker is in a casual setting."
# [29] "try to remember what he or she say or thinking about the speech"
# [30] "It can tell about hesitancy."
# [31] "They may be more hesitant and certain of what they are saying"
# [32] "Thinking, potentially lack of preparation for the topic. Reluctance, hesitancy, but more often just to avoid awkward gaps when searching for words."
# [33] "I think most of the time its purely just a habitual thing that we add when we are forming our next sentences and thoughts, but it can also indicate hesitation in making a decision or something which I definitely picked up on"
# [34] "hesitation, stalling to formulate a sentence"
# [35] "They're thinking about what to say next."
# [36] "It means they're more hesistant to come off as impolite usually. They are trying proabbly subconsciously to tell the other person that they would rather not bring up the topic rather than jump right in."
# [37] "Hesitation/being unsure of oneself, but also sometimes intelligence, as you're waiting for your brain to provide something intelligent instead of just blurting it out loud"
# [38] "Maybe slightly greater hesitancy, slightly lower levels of masculinity, more casual."
# [39] "I think it means that they are slightly more hesitant or are trying to think about their response."
# [40] "They are pausing to think about what they want to say, they are nervous, they are hesitant to say what they really feel."
# [41] "I think it means that they are thinking of what to say next or are not confident with their knowledge or understanding on a subject."
# [42] "Hesitation/nervousness/unsure how to proceed"
# [43] "hesitation, non-canadian, possibly non-heterosexual"
# [44] "They are unsure about something"
# [45] "it's a filler word used in situations to \"buy time\" to find the appropriate word/ correspondence/ gather your thoughts"
# [46] "i think it's just a habit, and a subconscious tactic people use when they are thinking of what to say next and are stalling for time (to avoid awkward silence); to signify that they have more to say still"
# [47] "I think it means that someones mouth is moving faster than their brain can process information so they are forced to use uh or um as a replacement"
# [48] "To keep the flow going and give pause for thought. "
# [49] "they are hesitant to say something "
# [50] "They are hesitant and think they are in more trouble than they actually are or don't know how to communicate a position they do not like. "
# [51] "More hesitant, trying to think before they continue"
# [52] "It means they are a little hesitant or they're trying to think of ways to be more polite and considerate. Often used when you don't know what to say right away as it gives you some extra time to think"
# [53] "it means that they are trying to think what they are about to say or that english is not their first language"
# [54] "I think that it means that there is hesitation or uncertainty. Also i think that they allow people longer to think about what they want to say about something"
# [55] "it means they are hesitant to talk about the topic they are about to talk about"
# [56] "Uncertainty and/or nervousness"
# [57] "Fillers instead of pausing to think"
# [58] "I feel like is has many meanings. Mainly, the speaker doesn't want to sound to harsh (a certain tone of \"uh\" or \"um\" could perhaps be used to deliver bad news in a more polite manner), they want to sound sassy, they want to sound casual, or they are unsure of what to say/are nervous."
# [59] "I think that it suggests that a person is hesitant, shy, embarrassed or nervous."
# [60] "hesitant, unsure. "
# [61] "I think when people say this, it means they know what they want to say but are still formulating the word order in their head. Starting the conversation before word formulation causes a delay which is filled by uh or um. This could actually indicate less hesitancy as a hesitant person would carefully formulate the words before speaking."
# [62] "I think it suggests hesitance or uncertainty in the speaker."
# [63] "They are having trouble finding the next word/phrase, or they need a bit of time to come up with it."
# [64] "They are speaking before they have completed their thought process."
# [65] "It is very often just a formed habit, I perceive nervousness and hesitation"
# [66] "That they have not formulated their thoughts enough to express them"
# [67] "unsure of themselves or trying to convey something uncomfortable"
# [68] "Thinking about how/what to say, sometimes hesitation"
# [69] "It is his/her way of taking a moment to think of what to say next, pausing to take a breath or just connecting two sentences. "
# [70] "It makes it less formal, and the person maybe trying to think of what to say. Which shows hesitation"
# [71] "I think that it can mean someone is unsure, insecure, or maybe it's just a speech habit."
# [72] "they are hesitating or on a trail of thought"
# [73] "I myself am a user of these words, probably these are used when you can't decide what is to be said."
# [74] "it might mean hesistation or in the process of thinking or just a habit"
# [75] "I think those words are almost subconscious things you say when you're still forming a sentence in your head as you speak."
# [76] "I think it means that the speaker is unsure of themselves or what they are going to say"
# [77] "Indicates some hesitation"
# [78] "When I use it, it just means I'm trying to formulate what I'm going to say next. I judge the recordings harsher than I would have judged someone in real life, so I thought they made her sound less intelligent (but they were continuous with the sentences, so I'm not really sure how they affected the hesitancy."
# [79] "I think it means that either the person is thinking or is trying to come up with something to say and uses filler words to avoid awkward pauses and silence"
# [80] "It means that they are unsure of the word that comes next possibly because of shyness or just confusion but also because they may be hesitant."
# [81] "It means that the person is stalling for time thinking of what to say next, or that they are trying to come off sounding less aggressive and more friendly"
# [82] "I think it has to do with if an individual is unsure or they are more casual when they speak or it is an indicator that they are more introverted "
# [83] "It may mean they are thinking over their thoughts before actually speaking"
# [84] "More hesitant, unsure and uncomfortable in sharing their feelings or responses with who they are talking to. "
# [85] "They are hesitant or thinking "
# [86] "That they are trying to express something that is not fully thought through, or they are scared"
# [87] "Either very comfortable or very nervous in the context of the situation"

afterbrief$Q2
#  [1] "No, I think they're the same"
#  [2] "uh-is more of a pause in thought    um-that you dont know what to say"
#  [3] "Personally, I think it's just a habit. Some people choose to say um while other say uh. However, personally, I'd say um more when I'm thinking of something to say and use uhh if I'm speaking faster than I can think of what I want to say. Uh is a placeholder for \"Hey. I'm still in the same train of thought. My brain just doesn't want to process as fast as I need it\" while umm would be like \"Oh, I haven't decided what I want to say. please hold.\""
#  [4] "\"um\" is used when thinking, whereas \"uh\" is used as fillers or to indicate doubt"
#  [5] "I think um and uh are interchangeable."
#  [6] "I think they have the same meanings, and people just have preferences of one over the other."
#  [7] "I think \"um\" is used when a person is thinking about an answer. I think \"uh\" is used when somebody is hesitant or reluctant to answer."
#  [8] "um seems more nervous than uh - uh seems like they lost their train of thought"
#  [9] "um is more self-aware and self-deprecating"
# [10] "I think they're relatively similar."
# [11] "I think that um is said more to when the person is anxious and or trying to reorganise the things they are trying to say whereas I perceive uh as when someone does not know what they want to say and or is confused"
# [12] "I think um is used more for actual thinking/hesitance. Uh is more of a conversation filler"
# [13] "\"Um\" could be more of an uncertain term associated with not knowing what you're going to say. \"Uh\" feels like just a pause before getting on with what you're going to say."
# [14] "in passing conversation, i don't think they have different meanings. however, when they're drawn out in pause, i find that \"um\" sounds more polite and formal compared to \"uh\". in cases in say, a presentation, saying \"um\" for some reason makes me think that they have it more together than someone who says \"uh\""
# [15] "Slightly, although I believe that both imply a kind of thinking meaning um seems somewhat deeper"
# [16] "I think \"uh\" is more vacuous and is said in other places (e.g. forgetting the next word in a sentence) whereas \"um\" has more meaning as a hedging word."
# [17] "Um I typically perceive as being used more in instances where people know what they think and what they are going to say, but they want to pause for whatever reason. I typically view uh as meaning that the person needs a second to gather their thoughts."
# [18] "I do not think that they have different meanings"
# [19] "I don't think so? But maybe they're used differently when we're mid-saying vs thinking about what to say next"
# [20] "Not necessarily, I think some people do use one more over the other."
# [21] "um is more like thinking while uh is more like something is hard to say"
# [22] "\"Um\" can express doubt, while \"uh\" just gives you time to think? But they can both be used in either way."
# [23] "Not sure."
# [24] "not really; i think um is more uncertain & hesitant"
# [25] "um i feel is more for thinking of an answer and uh is more for confusion or scrambling"
# [26] "they seem about the same to me"
# [27] "I do not associate um and uh with different meanings. However, I do think um seems more hesitant than using uh based on instinct. "
# [28] "before the experiment i did not think about it but now i thing um is more feminine "
# [29] "I think um means that the person need time to answer but uh means he/she does not want to answer or wants to change the topic."
# [30] "I think they are more or less the same"
# [31] "Usually think of \"um\" as higher pitched than \"uh\"."
# [32] "uh might be more masculine"
# [33] "Not sure"
# [34] "Um is more deliberate, uhh is more likely than um to be a pause in thought."
# [35] "Uh seems to be the less intelligent form. Um seems more relatable, and even kind of cute sometimes"
# [36] "No I don't, as personally I switch between both pretty easily."
# [37] "To me, \"Um,\" is a word that would generally be used if you are pausing to think about what to say/how to answer a question, and I would think that \"Uh\" is generally used during hesitation, nervousness. "
# [38] "Perhaps \"um\" means that the respondent is thinking of an answer they already know about and are trying to put their thought into words, and perhaps \"uh\" indicates that a person is caught by surprise or genuinely does not know how to respond or react."
# [39] "Um is more nervous/hesitant, uh is more a placeholder when searching for something to say"
# [40] "Um is more unsure about things"
# [41] "i think um gets used when you forget things where as uh is when you're pressed for an immediate response and cannot reply"
# [42] "i think \"um\" in some contexts can come off as more judgemental, but i think both are generally the same"
# [43] "No, I use them interchangeably. "
# [44] "uh is more of like if there is something you are genuinely unsure of, um is the same variant but a little more negative "
# [45] "No. "
# [46] "I typically use um when I'm thinking and uh when I'm speechless"
# [47] "I think \"um\" is used when someone is trying to think of what to say when \"uh\" is more about hesitancy"
# [48] "no"
# [49] "I think that they generally have the same meanings"
# [50] "i feel like \"um\" is when you are not sure about something, but \"uh\" is when you are sure but don't want to argue what you think is right or speak your mind entirely."
# [51] "No"
# [52] "I think people use um when trying to gather thoughts to form a sentence while uh is used when trying to remember something"
# [53] "Um feels more \"dainty\" to me. Now that I think about it, I think I would use it a bit more in professional settings if I had to say \"um\" or \"uh\". \"Uh\" could get more \"annoying\" when stretched and sound more childish."
# [54] "I think um is used more in situations where a person is shy or nervous (i.e. um, excuse me), whereas uh is more frequently used in situations where you cannot think of a better word to use (i.e. uh-oh, or uh, I think I broke your mug)"
# [55] "I think they roughly mean the same. "
# [56] "I think they have the same meaning, but to me um seems more feminine and uh seems more masculine. Perhaps this is due to um being said the mouth closed, and uh being said with the mouth open. "
# [57] "\"Uh\" would suggest a level of annoyance, whereas \"um\" would relate to a general uncertainty."
# [58] "No, I think they are interchangeable. "
# [59] "No, I think that they both serve the same purpose and therefore have the same definition. "
# [60] "I associate uh more with hesitation and um more with thinking/filler"
# [61] "For some reason, uh seems to have more of a loss for thoughts altogether and um seems to be that there is a thought but its not yet formed properly"
# [62] "uh is more uncertainty, um is more uncomfortable"
# [63] "I don't think I see them differently"
# [64] "Not really. I have always used them interchangeably in conversations. "
# [65] "I'm not sure"
# [66] "I think that um can mean that a person is considering something while uh is perhaps more of an involuntary hesitation."
# [67] "nope"
# [68] "I don't think so. Perhaps they're both used to take a um, a pause."
# [69] "i think they could be used similarly, although uh might sound a bit with more hesistation or not sure"
# [70] "I don't think um and uh have different meanings. "
# [71] "I think \"um\" suggests more uncertainty and nervousness about what one is about to say. \"Uh\" suggests more of a delay or that the speaker is searching for a particular word  "
# [72] "No"
# [73] "Not really."
# [74] "\"Uh\" sounds like you're thinking or processing information you've just learned, while \"um\" tends to sound like you're trying to find words to say and/or making up speech without thinking it through"
# [75] "I feel that um is more used in social settings where the speaker is unsure or perhaps more introverted while I think uh is more of an informal yet connecting word used by friends and such."
# [76] "Not really, but I guess I would say that \"um\" is for a longer pause, while \"uh\" would be just a brief pause."
# [77] "I feel like they can be used interchangeably as they both can equate to hesitation "
# [78] "\"um\" may be a bit more polite possibly due to the fact that you have your mouth closed during this phrase while with \"uh\", your mouth is wide open and could be rude to someone talking to you if you held it for too long"
# [79] "Uh to me would be more used in a setting of surprise where one would need to think about the answer. Um sounds more uncomfortable to me, as if the person saying it knows the answer/what they want but is uncomfortable sharing that."
# [80] "Yes. Umm.. is like prolonging a decision and uh is for thinking purposefully"
# [81] "Uh to me seems more like filler for thinking, while um seems to be filler for making a decision while thinking"
# [82] "I dont think so"
